# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Edit_column.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditColumn(object):
    def setupUi(self, EditColumn):
        EditColumn.setObjectName("EditColumn")
        EditColumn.resize(450, 600)
        self.centralwidget = QtWidgets.QWidget(EditColumn)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 401, 531))
        self.groupBox.setObjectName("groupBox")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(20, 30, 361, 481))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 479))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 361, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(17)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        EditColumn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditColumn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 22))
        self.menubar.setObjectName("menubar")
        EditColumn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditColumn)
        self.statusbar.setObjectName("statusbar")
        EditColumn.setStatusBar(self.statusbar)

        self.retranslateUi(EditColumn)
        QtCore.QMetaObject.connectSlotsByName(EditColumn)

    def retranslateUi(self, EditColumn):
        _translate = QtCore.QCoreApplication.translate
        EditColumn.setWindowTitle(_translate("EditColumn", "MainWindow"))
        self.groupBox.setTitle(_translate("EditColumn", "Assign Column"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("EditColumn", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("EditColumn", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("EditColumn", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("EditColumn", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("EditColumn", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("EditColumn", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("EditColumn", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("EditColumn", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("EditColumn", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("EditColumn", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("EditColumn", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("EditColumn", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("EditColumn", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("EditColumn", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("EditColumn", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("EditColumn", "16"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("EditColumn", "Column Number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("EditColumn", "Column Sections"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("EditColumn", "11"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("EditColumn", "12"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("EditColumn", "13"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("EditColumn", "14"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("EditColumn", "15"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("EditColumn", "16"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("EditColumn", "17"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("EditColumn", "18"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("EditColumn", "19"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("EditColumn", "20"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("EditColumn", "21"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("EditColumn", "22"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("EditColumn", "23"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("EditColumn", "24"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("EditColumn", "25"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("EditColumn", "V1"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("EditColumn", "26"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("EditColumn", "V1"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditColumn = QtWidgets.QMainWindow()
    ui = Ui_EditColumn()
    ui.setupUi(EditColumn)
    EditColumn.show()
    sys.exit(app.exec_())
