#Project_Settings
setting,value
tower_elevs,0.0 6.0 9.0 12.0 15.0 18.0 21.0 27.0 33.0 39.0 45.0 51.0 57.0 60.0
sect_props,BALSA_0.5x0.5 1
sect_props,BALSA_0.1875x0.1875 2
sect_props,BALSA_13/16_HOLLOW 3
sect_props,BALSA_13/16_CROSS 4
sect_props,BALSA_TRIPLE 5
gm,True
analysis,Time_History
modelLoc,C:/Users/Kaison/Downloads/Base.sdb
modelName,Base.sdb
renderX,12.0
renderY,12.0
renderZ,60.0
SAPPath,C:\Program Files\Computers and Structures\SAP2000 22\SAP2000.exe
nodesList,1 2 3 4
footprint,144
totalHeight,60
totalMass,7.83
gmIdentifier,GM1
toRun,False

#Display_Settings
setting,value
2D_pName,True
2D_pLength,False

#Floor_Plans
floorPlanName,x,y,bot,top
L_shape,0.0,0.0,1,1
L_shape,4.5,0.0,2,2
L_shape,4.5,7.5,3,3
L_shape,12.0,7.5,4,4
L_shape,12.0,12.0,5,5
L_shape,0.0,12.0,6,6
Diamond,0.0,0.0,1,1
Diamond,4.5,0.0,2,2
Diamond,12.0,7.5,3,3
Diamond,12.0,12.0,4,4
Diamond,0.0,12.0,5,5

#Floors
elevation,floorPlans
0.0,L_shape
6.0,L_shape
9.0,L_shape
12.0,L_shape
15.0,L_shape
18.0,L_shape
21.0,L_shape Diamond
27.0,Diamond
33.0,Diamond
39.0,Diamond
45.0,Diamond
51.0,Diamond
57.0,Diamond
60.0,Diamond

#Panels
panelName,nodeLocation,x,y,z

#Bracings
bracingName,x1,y1,x2,y2,material
default,0.0,0.0,0.0,1.0,BALSA_0.5x0.5
default,0.0,1.0,1.0,1.0,BALSA_0.5x0.5
default,1.0,1.0,1.0,0.0,BALSA_0.5x0.5
default,1.0,0.0,0.0,0.0,BALSA_0.5x0.5
X,0.0,0.0,0.5,0.5,BALSA_0.1875x0.1875
X,0.5,0.5,1.0,0.0,BALSA_0.1875x0.1875
X,0.5,0.5,1.0,1.0,BALSA_0.1875x0.1875
X,0.5,0.5,0.0,1.0,BALSA_0.1875x0.1875

#Bracing_Groups
bracingGroup,bracing

#Section_Groups
sectionGroup,section

#Bracing_Assignments
panelName,bracingGroup

#Section_Assignments
memberid,sectionGroup
