#PATHS
Project_settings,C:\Users\shirl\OneDrive - University of Toronto\Desktop\Seismic\Autobuilder-3.0\Test Files\autobuilder\projectSettings.csv,
Floor_plans,C:\Users\shirl\OneDrive - University of Toronto\Desktop\Seismic\Autobuilder-3.0\Test Files\autobuilder\floorPlan.csv,
Panels,C:\Users\shirl\OneDrive - University of Toronto\Desktop\Seismic\Autobuilder-3.0\Test Files\autobuilder\panel.csv,
Bracings,C:\Users\shirl\OneDrive - University of Toronto\Desktop\Seismic\Autobuilder-3.0\Test Files\autobuilder\bracings.csv,